name: DockerImageCI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'apps/flask-app-v3/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'apps/flask-app-v3/**'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: chamambom/guess
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: apps/flask-app-v3/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}