name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'apps/flask-app-v3/**'
      - '.github/workflows/docker-image-CI.yaml'
  # pull_request:
  #   branches: [ "main" ]
  #   paths:
  #     - 'apps/flask-app-v3/**'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set Docker image version
        run: echo "1.0.0" > IMAGE_VERSION
        id: version

      - name: Upload version to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: version
          path: IMAGE_VERSION
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Download version artifact
        uses: actions/download-artifact@v2
        with:
          name: version
          path: .
      
      - name: Read version from file
        run: IMAGE_VERSION=$(cat IMAGE_VERSION)
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: apps/flask-app-v3/
          file: apps/flask-app-v3/Dockerfile
          push: true
          tags: v1